### PR TITLE
Issue 51 terminology

### PR DESCRIPTION
**Pull request by murata2makoto**
This is to address #51 .

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ruby-t2s-req/pull/52.html" title="Last updated on Jul 6, 2024, 12:27 AM UTC (3c6f4fd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ruby-t2s-req/52/8affefd...3c6f4fd.html" title="Last updated on Jul 6, 2024, 12:27 AM UTC (3c6f4fd)">Diff</a>

### CODE REVIEW

**Comment by kidayasuo** [comment]
I am a bit concerned that there are parts where the author’s opinions appear to be overly reflected in the writing. One example I noticed is the section about jukugo-ruby. I believe it should simply mention the benefits of each method, right?

[A single ruby element or multiple ruby elements per one compound word](https://pr-preview.s3.amazonaws.com/w3c/ruby-t2s-req/pull/52.html#a-single-ruby-element-or-multiple-ruby-elements-per-one-compound-word)

**Comment by murata2makoto** [comment]
>I am a bit concerned that there are parts where the author’s opinions appear to be overly reflected in the writing. 

I would like to merge this pull request first and then address such parts later.  Please create separate issues for each of such parts.  

>One example I noticed is the section about jukugo-ruby. I believe it should simply mention the benefits of each method, right?

This is actually based on Okayama-san's and Florian's opinions.  But I vaguely remember that one guy involved in JP DAISY textbooks has a different opinion.  Don't know benefits of the approach of two `<ruby>` elements though.

**Comment by murata2makoto** [comment]
I know that a group of JP DAISY experts create multiple ruby elements per one compound word (one for each CJK character).  But do other people do so?  I have no supporting evidence.

**Comment by murata2makoto** [comment]
I find a good reason from the email archive of the JP DAISY Consortium.  How about this?

However, there is a good reason to attach ruby annotations to some, but not all, characters in a compound word.  For example, consider <span lang="ja">佳人</span>, where <span lang="ja">佳</span> is taught in junior high schools while <span lang="ja">人</span> is taught in the first grade of elementary schools.  Thus, it is natural to attach a ruby annotation to <span lang="ja">佳</span> only.  Thus, `<ruby><rb><span lang="ja">佳</span></rb><rt>か</rt></ruby>人` is commonly used.

**Review by kidayasuo — APPROVED** [review]
approving. thank you!

**Pull request merged**
